### ISSUE TITLE
cannot migrate

### ISSUE THREAD

**Issue by 9818679544** [nahid/talk-example#1]
Warning: require(C:\xampp\htdocs\chat\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in C:\xampp\htdocs\chat\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\chat\bootstrap/../vendor/autoload.php' (include_path='.;C:\xampp\php\PEAR') in C:\xampp\htdocs\chat\bootstrap\autoloa
d.php on line 17

**Comment by nahid** [comment]
give me details

**Comment by moritzwelsch** [comment]
Try "composer install", it will fix de missing dependencies
