### ISSUE TITLE
Pusher didnt receive the request

### ISSUE THREAD

**Issue by realz77** [nahid/talk-example#15]
Hello Nahid,

I followed all the steps but it ain't work ! it works only if i refresh the page :(
Can u tell us a way to set a debug mode ?

I'm using Pusher, when i post a message, its not even count in pusher dashboard and i have no errors when inspecting ajax post request on my browser.

Config/talk
```
<?php
return [
    'user' => [
        'model' => 'App\User'
    ],
    'broadcast' => [
        'enable' => true,
        'app_name' => 'laravel-iehr-talk',
        'pusher' => [
            'app_id'        => env('PUSHER_APP_ID'),
            'app_key'       => env('PUSHER_KEY'),
            'app_secret'    => env('PUSHER_SECRET'),
            'options' => [
                 'cluster' => 'eu',
                 'encrypted' => true
            ]
        ]
    ]
];
```
.env

```
PUSHER_APP_ID='366090'
PUSHER_KEY='774fd532de1980fb8bf3'
PUSHER_SECRET='******secret*****'
```
artisan
![dsqe](https://user-images.githubusercontent.com/25646089/28096520-c3d40dc0-66a9-11e7-8780-1f00847d6606.png)

Alex

**Comment by realz77** [comment]
do it requires nodejs server ?

**Comment by nahid** [comment]
Nope, nodejs didn't required. do you update Talk with latest version?

**Comment by realz77** [comment]
i have these versions : 
```
        "nahid/talk": "^2.2",
        "vinkla/pusher": "^2.4",
        "pusher/pusher-php-server": "^2.6",
        "predis/predis": "^1.1"
```
Actually, i tested on Laragon server and it works, but i want it work on wamp, do you know the problem?

Thanks a lot

**Comment by nahid** [comment]
please update Talk with version 2.2.1

**Comment by realz77** [comment]
i'm now working on laragon and it works online so its fine thank you !
Btw great package, did you plan to include multiple conversations and file upload in the future?

**Comment by nahid** [comment]
Yep, I'm working on it. May be it will comes with in next release.
