### ISSUE TITLE
Help in installing on a real project

### ISSUE THREAD

**Issue by catumd** [nahid/talk-example#17]
Hi, thank for your job, this repository in full satisfy the need for my project bad one problem I don't know how to install  this example in my project, I tried but brought this error to the main screen `InvalidArgumentException in AuthManager.php line 86:
Auth guard [user] is not defined.`  what to do? 
How can I insert talk-example into my applications?

**Comment by nahid** [comment]
If you want to develop messaging system please integrate http://github.com/nahid/talk with your system.

Talk-Example is a demo project for `Talk`

**Comment by catumd** [comment]
@nahid,  Yes,  but I don't  experience in creating a real-time chat because I  try using this example.

**Comment by catumd** [comment]
@nahid good I did, I  add in  MessageController.php in public function __construct() this code `$this->middleware(function ($request, $next) {
            Talk::setAuthUserId(Auth::user()->id);
            return $next($request);
        });
        
        View::composer('partials.peoplelist', function ($view) {
            $threads = Talk::threads();
            $view->with(compact('threads'));
        });` and everything turned out.

**Comment by nahid** [comment]
You can use Talk Middleware for laravel 5.3+

register this middleware in `app/Http/Kernel.php` in routeMiddleware section

```php
'talk'  =>  \Nahid\Talk\Middleware\TalkMiddleware::class,
```

**Comment by catumd** [comment]
That's exactly what I did.
