### ISSUE TITLE
I have to refresh the page for the new message

### ISSUE THREAD

**Issue by baig772** [nahid/talk-example#19]
Every time I hit send, I have to refresh the page for the receiver end to get the new message. Followed the steps exactly. Don't see any output after `php artisan:queue listen`

**Comment by nahid** [comment]
Update talk with version `v2.2.1` and replace config file with this code

```php
<?php
return [
    'user' => [
        'model' => 'App\User',
    ],
    'broadcast' => [
        'enable' => false,
        'app_name' => 'your-app-name',
        'pusher' => [
            'app_id' => '',
            'app_key' => '',
            'app_secret' => '',
            'options' => [
                'cluster' => 'ap1',
                'encrypted' => true
            ]
        ],
    ],
];
```

**Comment by baig772** [comment]
I still have to refresh the page to see the new messages. I am trying it on my local system and signed in form 2 different users on 2 different browsers. Will it work on local?

**Comment by nahid** [comment]
please share `config/talk.php` file

**Comment by baig772** [comment]
Below is my talk.php
`<?php
return [
    'user' => [
        'model' => 'App\User',
    ],
    'broadcast' => [
        'enable' => true,
        'app_name' => 'heroic-salute-582',
        'pusher' => [
            'app_id' => env('PUSHER_APP_ID'),
            'app_key' => env('PUSHER_KEY'),
            'app_secret' => env('PUSHER_SECRET'),
            'options' => [
                'cluster' => 'ap1',
                'encrypted' => true
            ]
        ],
    ],
];`

**Comment by nahid** [comment]
Is your cluster is correct?

**Comment by baig772** [comment]
changed the cluster to correct one i.e `eu` but still same

**Comment by baig772** [comment]
Is there any update on this?

**Comment by Ravenna** [comment]
I also have this issue.  I have updated to talk 2.2.1 and I have the correct cluster set.

**Comment by nahid** [comment]
Talk-Example is now `Docker` ready. All dependancies are now bring with docker. Just run this command and update your credentials and enjoy ...

```
./talk ready
```
