### ISSUE TITLE
Conflict with Pusher PHP server v^3.0

### ISSUE THREAD

**Issue by Lexx-YungCarter** [nahid/talk-example#24]
There seems to be a conflict between this package and pusher-php-server v3.0 onwards. Here are the errors I encounter while trying out a `composer update` . Any fixes or a possible workaround for this? 

`"require": {
        "php": ">=5.6.4",
        "laravel/framework": "5.3.*",
        "sebastian-berc/repositories": "^1.0",
        "yohang88/letter-avatar": "^1.0",
        "vinkla/pusher": "^3.0",
        "pusher/pusher-php-server": "^3.0",
        "predis/predis": "^1.1",
        "nahid/talk": "^2.2"
    },
    "require-dev": {
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "0.9.*",
        "phpunit/phpunit": "~5.0",
        "symfony/css-selector": "3.1.*",
        "symfony/dom-crawler": "3.1.*"
    },

`

`Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nahid/talk v2.2.1 requires pusher/pusher-php-server ^2.6 -> satisfiable by pusher/pusher-php-server[2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.x-dev, v2.6.0] but these conflict with your requirements or minimum-stability.
    - nahid/talk v2.2.0 requires pusher/pusher-php-server ^2.6 -> satisfiable by pusher/pusher-php-server[2.6.1, 2.6.2, 2.6.3, 2.6.4, 2.x-dev, v2.6.0] but these conflict with your requirements or minimum-stability.
    - Installation request for nahid/talk ^2.2 -> satisfiable by nahid/talk[v2.2.0, v2.2.1].`

**Comment by nahid** [comment]
use `"nahid/talk": "dev-master"` instead of `"nahid/talk": "^2.2"`

**Comment by Lexx-YungCarter** [comment]
It works now!

**Comment by ivanzhujunwei** [comment]
Hi, I also got this issue, but, sorry, I don't know how to use **"nahid/talk": "dev-master"** insetad of **"nahid/talk": "^2.2"**? since I just input the "composer install".

**Comment by Metourni** [comment]
I have the same problem
```

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "askedio/laravel-soft-cascade": "^5.8",
        "barryvdh/laravel-cors": "^0.11.3",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "5.8.*",
        "laravel/passport": "^7.2",
        "laravel/tinker": "^1.0",
        "pusher/pusher-php-server": "~3.0",
        "ext-json": "*"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^3.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}

```
