### ISSUE TITLE
Server pusher don't send message to pusher debug console

### ISSUE THREAD

**Issue by ATNoosh** [nahid/talk-example#29]
Hi.
I installed nahid talk v2.2.1 on laravel 5.2. Using talk_live helper, subscription messages are visible in debug console in pusher account. But server pusher don't send any message to the pusher.com server. My config in talk.php is correct. In the Broadcast.php $pusher object is ok but $pusher->get_channels() returns null.

I traced the code in ajaxSendMessage. Then Talk::sendMessageByUserId($userId, $body) called. Then sendMessageByUserId. Then makeMessage inside Talk.php. Then line         
$this->broadcast->transmission($message);
transmission in Broadcast.php returns false because the $pusher is null.

I noticed to the Debug Console in pusher, about 5 seconds after subscription to the channels, channels Disconnection occur in some cases.

**Comment by nahid** [comment]
Please share your config

**Comment by ATNoosh** [comment]
<?php

return [
    'user' => [
        'model' => 'App\User',
    ],
    'broadcast' => [
        'enable' => true,
        'app_name' => 'my-app-name',
        'pusher' => [
            'app_id' => '------',
            'app_key' => '--------------------',
            'app_secret' => '--------------------',
            'options' => [
                'cluster' => '---',
                'encrypted' => true
            ]
        ],
    ],
];

**Comment by ATNoosh** [comment]
Of course I also tested below config:
<?php

return [
    'user' => [
        'model' => 'App\User',
    ],
    'broadcast' => [
        'enable' => false,
        'app_name' => 'my-app-name',
        'pusher' => [
            'app_id' => '------',
            'app_key' => '--------------------',
            'app_secret' => '--------------------',
            'options' => [
                'cluster' => '---',
                'encrypted' => true
            ]
        ],
    ],
];

**Comment by Bobyuan1015** [comment]
have you solved this problem

**Comment by ATNoosh** [comment]
Yes. I solved myself.
I found that my config attributes in the vendor/talk are empty. So changed the talk code to use my hard code config.

**Comment by nahid** [comment]
please share your changes
