### ISSUE TITLE
 http://localhost:8000/ajax/message/send 500 (Internal Server Error)

### ISSUE THREAD

**Issue by Bobyuan1015** [nahid/talk-example#30]
when I click send, there is an err of  http://localhost:8000/ajax/message/send 500 (Internal Server Error)

**Comment by joshchisnerman** [comment]
Same here. Any solution?

**Comment by marslan2037** [comment]
any solution ?

**Comment by nahid** [comment]
please show me the error logs

**Comment by marslan2037** [comment]
@nahid new installation is not working now

**Comment by nahid** [comment]
Please try this project with `docker`. If you have already installed docker, run this command and enjoy

```
./talk ready
```
