### ISSUE TITLE
Unable to install Pusher

### ISSUE THREAD

**Issue by yasser4ever1** [nahid/talk-example#32]
Hello,

I wanted to install pusher using this command `composer require pusher/pusher-php-server
` so i can make notifications of new messages from Laravel Talk but i get this error whenever i try to install pusher
![capture](https://user-images.githubusercontent.com/2912056/37276343-18591764-25ea-11e8-8fb2-490d8f0350c9.JPG)

**Comment by nahid** [comment]
please try this project with `docker`. If you have already installed docker then this command and enjoy.

```
./talk ready
```

for details read the doc
