### ISSUE TITLE
Unable to do composer install

### ISSUE THREAD

**Issue by marslan2037** [nahid/talk-example#34]
after downloading package, when i do composer install, it gives this error,

Source path "pkgs/nahid/talk" is not found for package nahid/talk

**Comment by nahid** [comment]
Please try with `docker`. You have already installed docker on you machine then run this command 

```shell
./talk ready
```

**Comment by nahid** [comment]
ok, if haven't any idea about docker then please try with latest commit. This problem was solved

**Comment by marslan2037** [comment]
ok, let me try

**Comment by marslan2037** [comment]
@nahid it gives error when i run php artisan migrate

**Comment by marslan2037** [comment]
what i did is, 
1) download latest zip file
2) run composer install
3) php artisan migrate
but it gives error

> [Illuminate\Database\QueryException]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No suc
  h host is known.  (SQL: select * from information_schema.tables where table
  _schema = realtime_chat and table_name = migrations)



  [PDOException]
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: No suc
  h host is known.



  [PDOException]
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: No such h
  ost is known.

**Comment by nahid** [comment]
make sure you have set valid database credentials

**Comment by marslan2037** [comment]
yes its fine

**Comment by marslan2037** [comment]
i missed anything ?

**Comment by marslan2037** [comment]
it works, my mistake, but no when hit send button i get this error

> Failed to load resource: the server responded with a status of 500 (Internal Server Error)

**Comment by marslan2037** [comment]
this is the error i have in console 

> Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4005,"message":"Path not found"}}}

> Pusher : State changed : connecting -> disconnected

**Comment by marslan2037** [comment]
i have to add credentials in .env file to fix this error, but now new error 

> php_network_getaddresses: getaddrinfo failed: No such host is known. [tcp://redis:6379]

**Comment by marslan2037** [comment]
this error in preview tab...

**Comment by nahid** [comment]
maybe you missed to run `./talk ready` command. Make sure you have already installed Docker on your machine.
