### ISSUE TITLE
Pusher Error

### ISSUE THREAD

**Issue by marslan2037** [nahid/talk-example#35]
These are the steps i follow 

1) Download latest zip file,
2) run command ./talk ready
3) composer install
4) add pusher credentials
5) php artisan migrate
6) create account
7) click on message button
and it gives error

> Pusher : Error : {"type":"WebSocketError","error":{"type":"PusherError","data":{"code":4001,"message":"Did you forget to specify the cluster when creating the Pusher instance? App key ff002e63cfa0ec7812c0 does not exist in this cluster."}}}

can you please help me on this, i have docker installed in my laptop

**Comment by marslan2037** [comment]
@nahid please check this, i have this error,

**Comment by nahid** [comment]
see #10

**Comment by marslan2037** [comment]
@nahid i already check it, and on that issue @waseemsafder give a solution when i check that file i do not find anything related to encrypted: true

**Comment by marslan2037** [comment]
this is what it does when i run ./talk ready command , https://imgur.com/a/dhXlsgw ,nothing else
