### ISSUE TITLE
there is no helper/talk.php

### ISSUE THREAD

**Issue by knuks** [nahid/talk-example#4]
when we run php artisan migrate there are a errors for ././helpers/talk.php not found

**Comment by nahid** [comment]
Remove this line from `composer.json` file.

```json
  "files": [
            "nahid/talk/src/helpers/talk.php"
        ]
```

**Comment by knuks** [comment]
Warning: require(C:\xampp\htdocs\talk\vendor\composer/../../nahid/talk/src/helpers/talk.php): failed to open stream: No such file or directory in C:\xampp\htdocs\talk\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\xampp\htdocs\talk\vendor\composer/../../nahid/talk/src/helpers/talk.php' (include_path='C:\xampp\php\PEAR') in C:\xampp\htdocs\talk\vendor\composer\autoload_real.php on line 66

I got when migrate database

**Comment by knuks** [comment]
i also removed from composer.json but not working

**Comment by nahid** [comment]
run `composer dumpautoload`

**Comment by knuks** [comment]
ok done which page first run

**Comment by nahid** [comment]
run `php artisan serve` and goto you browser and run this url http://localhost:8000

**Comment by knuks** [comment]
thank you for reply but i got 
RuntimeException in Encrypter.php line 43:
The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.

**Comment by nahid** [comment]
run `php artisan key:generate`

**Comment by knuks** [comment]
nice app...and thank u to guide me for running this app
i have one suggestion for ur app to enhance the chat sound when message
arrived to user like facebook...
thank u very much
