### ISSUE TITLE
Call to undefined function talk_live()

### ISSUE THREAD

**Issue by ahmadbadpey** [nahid/talk-example#6]
After following all install instructions and set pusher configurations , I got this error at end of conversation page : 

```
FatalErrorException in 1903760f40f5627c0ec3eadb405d29c4805b8745.php line 91:
Call to undefined function talk_live()
```

I searched all project filed and did not found any `talk_live()` function declaration.

**Comment by nahid** [comment]
Use Talk latest version v2.1.2 @ahmadbadpey 

Maybe you use older version where talk did not support realtime messaging, thats why `talk_live()` is missing.

**Comment by ahmadbadpey** [comment]
I just downloaded your project from github and then run composer install . is not enough that ?

**Comment by nafiesl** [comment]
@ahmadbadpey i was got same error, just run `composer update`, it pulls `nahid/talk (v2.0.0 => v2.1.2)`, and no more error
